apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
- secrets/secrets.yaml
- secrets/tls.yaml
- secrets/credentials.yaml
- manifests/resourceQuota.yaml
- manifests/stockages.yaml
- manifests/configmaps.yaml
- manifests/redis.yaml
- manifests/mariadb.yaml
- manifests/ingress-tls.yaml
- manifests/php.yaml
- manifests/nginx.yaml
- manifests/cronjobs.yaml
